### PR TITLE
SAPP-1082: Adds local volume mount

### PR DESCRIPTION
**Pull request by acbramley**
Adds an emptyDir mount to `/local` for things like twig caches.

Requires projects to update scaffold to include https://github.com/universityofadelaide/shepherd-drupal-scaffold/pull/88/files (will need a new release for WCMS/Admission/Scholarships).

Can be tested with https://github.com/universityofadelaide/shepherd-example-drupal

Environment/Project config must pass the following environment variable:
```
LOCAL_DIR=/local
```

### CODE REVIEW

**Comment by acbramley** [comment]
Failures due to composer 2 issues.

**Comment by pingers** [comment]
Okay, we reaaaally need to fix that composer version.

**Comment by pingers** [comment]
@acbramley At least it's failing on linting now ;)

**Review by pingers — APPROVED** [review]
Updates openshift lib and declares the empty mount type - looks good to me :+1:

**Pull request merged**
